Models/Course.cs
namespace basic.Models{
    public class Course{
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Image { get; set; }
        public string? Description { get; set; }
        public string[]? Tags { get; set; }
        public bool isActive { get; set; }
        public bool isHome { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace basic.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Repository.cs
namespace basic.Models
{
    public class Repository
    {
        private static readonly List<Course> _courses = new();
        static Repository(){
            _courses = new List<Course>(){
                new Course() {
                    Id = 1, 
                    Title = "ASP.NET Core", 
                    Description = "Net Core Kursu", 
                    Image="1.jpg", 
                    Tags = new string[]{"aspnet","web","masaüstü","kodlama"},
                    isActive = true,
                    isHome = true 
                    },
                new Course() {
                    Id = 2, 
                    Title = "PHP", 
                    Description = "PHP Kursu", 
                    Image="2.jpg",
                    Tags = new string[]{"php","web","kodlama"},
                    isActive = true,
                    isHome = true 
                    },
                new Course() {
                    Id = 3, 
                    Title = "Ptyhon", 
                    Description = "Django Kursu", 
                    Image="3.jpg",
                    isActive = true,
                    isHome = true 
                    },
                new Course() {
                    Id = 4, 
                    Title = "Javascript", 
                    Description = "Javascript Kursu", 
                    Image="1.jpg",
                    Tags = new string[]{"js","web","kodlama"},
                    isActive = false,
                    isHome = true 
                    },
            };
        }

        public static List<Course> Courses{
            get{
                return _courses;
            }
        }

        public static Course? GetById(int id){
            return _courses.FirstOrDefault(x => x.Id == id);
        }
    }
}

Controllers/CourseController.cs
using basic.Models;
using Microsoft.AspNetCore.Mvc;

namespace basic.Controllers
{
    public class CourseController : Controller
    {
        public IActionResult List(){   
            return View("CourseList", Repository.Courses);
        }

        public IActionResult Detail(int id){
            if (Repository.GetById(id) == null)
            {
                return RedirectToAction("List");
            }

            var kurs = Repository.GetById(id);
            return View(kurs);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using basic.Models;

namespace basic.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View(Repository.Courses);
    }

    public IActionResult Contact()
    {
        return View();
    }
}

Views/Course/CourseList.cshtml
@model List<Course>
@foreach(var kurs in Model){
    @if(kurs.isActive){
        @await Html.PartialAsync("_Course", kurs)
    }
}   

Views/Course/Detail.cshtml
@model Course

<div class="row">
    <div class="col-md-4">
        <img src="~/img/@Model.Image" class="img-fluid rounded-start" alt="">
    </div>
    <div class="col-md-8">
        <a asp-controller="Course" asp-action="Detail" asp-route-id="@Model.Id">
            <h5 class="card-title">@Model.Title</h5>
        </a>
        <p class="card-text">@Model.Description</p>
        <div>
            @if(Model.Tags != null){
                @foreach(var tag in Model.Tags)
                {
                    <span class="badge bg-danger p-2">@tag</span>
                }
            }
        </div>
    </div>
</div>

Views/Course/Index.cshtml
@model Course
@await Html.PartialAsync("_Course", @Model)

Views/Course/_Course.cshtml
<div class="card mb-3" id="kurs_@Model.Id">
    <div class="row">                   
        <div class="col-md-4">
            <img src="~/img/@Model.Image" alt="@Model.Title" class="img-fluid" width="300">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <a asp-controller="Course" asp-action="Detail" asp-route-id="@Model.Id">
                    <h2 class="card-title">@Model.Title</h2>
                </a>
                <p class="card-text">@Model.Description</p>
            </div>
        </div>    
    </div>  
</div> 

Views/Home/Contact.cshtml
<h1>İletişim</h1>

Views/Home/Index.cshtml
@model List<Course>
<h1>Home Page</h1>

@section Header{
    @await Html.PartialAsync("_Header")
}  

<div class="row">
    @foreach(var kurs in Model)
    {
        @if(kurs.isActive && kurs.isHome){
        <div class="col-3">
            <div class="card">
                <img src="~/img/@kurs.Image" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">@kurs.Title</h5>
                    <p class="card-text">@kurs.Description</p>
                    <a class="btn btn-primary" asp-controller="Course" asp-action="Detail" asp-route-id="@kurs.Id">Detay</a>
                </div>
            </div>
        </div>
        }
    }
</div>

Views/Shared/_Header.cshtml
<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container py-5">
        <h1 class="display-5 fw-bold">Home Page</h1>
        <p class="col-md-8 fs-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ea, incidunt quaerat non repudiandae omnis accusamus voluptatibus aliquid deleniti unde iusto?
        </p>
        <button class="btn btn-primary btn-lg">Button</button>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <title>Kurslar</title>
</head>
<body>
    <header>
        @await Html.PartialAsync("_Navbar")
        @RenderSection("Header", false)
    </header>
    <div class="container mt-3">
        <main>
            @RenderBody()
        </main>
    </div>
</body>
</html>

Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-sm navbar-dark bg-success">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">CourseApp</a>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Course" asp-action="List">Kurslar</a>
            </li>
        </ul>
    </div>
</nav>